
export const ORDER_LIST = 'ORDER_LIST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR';

export const PAY_PARAMER = 'PAY_PARAMER';
export const PAY_PARAMER_SUCCESS = 'PAY_PARAMER_SUCCESS';
export const PAY_PARAMER_ERROR = 'PAY_PARAMER_ERROR';
