
export const ORDER_INFO = 'ORDER_INFO';
export const ORDER_INFO_SUCCESS = 'ORDER_INFO_SUCCESS';
export const ORDER_INFO_ERROR = 'ORDER_INFO_ERROR';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR';
