
export const BINDING = 'BINDING';
export const BINDING_SUCCESS = 'BINDING_SUCCESS';
export const BINDING_ERROR = 'BINDING_ERROR';

export const UNBIND_LIST = 'UNBIND_LIST';
export const UNBIND_LIST_SUCCESS = 'UNBIND_LIST_SUCCESS';
export const UNBIND_LIST_ERROR = 'UNBIND_LIST_ERROR';

export const GET_SIGN_PACKAGE = 'GET_SIGN_PACKAGE';
export const GET_SIGN_PACKAGE_SUCCESS = 'GET_SIGN_PACKAGE_SUCCESS';
export const GET_SIGN_PACKAGE_ERROR = 'GET_SIGN_PACKAGE_ERROR';
