
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_SUCCESS = 'HELLO_WORLD_SUCCESS';
export const HELLO_WORLD_ERROR = 'HELLO_WORLD_ERROR';

export const SUBSCRIBE = 'SUBSCRIBE';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_ERROR = 'SUBSCRIBE_ERROR';

export const IS_SUBSCRIBE = 'IS_SUBSCRIBE';
export const IS_SUBSCRIBE_SUCCESS = 'IS_SUBSCRIBE_SUCCESS';
export const IS_SUBSCRIBE_ERROR = 'IS_SUBSCRIBE_ERROR';

