
export const GOODS_PROGRESS_LIST = 'GOODS_PROGRESS_LIST';
export const GOODS_PROGRESS_LIST_SUCCESS = 'GOODS_PROGRESS_LIST_SUCCESS';
export const GOODS_PROGRESS_LIST_ERROR = 'GOODS_PROGRESS_LIST_ERROR';

export const BIND_USER_LIST = 'BIND_USER_LIST';
export const BIND_USER_LIST_SUCCESS = 'BIND_USER_LIST_SUCCESS';
export const BIND_USER_LIST_ERROR = 'BIND_USER_LIST_ERROR';
