
export const GOODS_ITEM = 'GOODS_ITEM';
export const GOODS_ITEM_SUCCESS = 'GOODS_ITEM_SUCCESS';
export const GOODS_ITEM_ERROR = 'GOODS_ITEM_ERROR';


export const IMAGE_TEXT = 'IMAGE_TEXT';
export const IMAGE_TEXT_SUCCESS = 'IMAGE_TEXT_SUCCESS';
export const IMAGE_TEXT_ERROR = 'IMAGE_TEXT_ERROR';


export const PROFESSIONAL = 'PROFESSIONAL';
export const PROFESSIONAL_SUCCESS = 'PROFESSIONAL_SUCCESS';
export const PROFESSIONAL_ERROR = 'PROFESSIONAL_ERROR';
