
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

export const PAY_PARAMER = 'PAY_PARAMER';
export const PAY_PARAMER_SUCCESS = 'PAY_PARAMER_SUCCESS';
export const PAY_PARAMER_ERROR = 'PAY_PARAMER_ERROR';

export const GET_OPEN_REGION = 'GET_OPEN_REGION';
export const GET_OPEN_REGION_SUCCESS = 'GET_OPEN_REGION_SUCCESS';
export const GET_OPEN_REGION_ERROR = 'GET_OPEN_REGION_ERROR';
