
//历史检测人
export const HISTORY_PERSON = 'HISTORY_PERSON';
export const HISTORY_PERSON_SUCCESS = 'HISTORY_PERSON_SUCCESS';
export const HISTORY_PERSON_ERROR = 'HISTORY_PERSON_ERROR';

export const GENE_GOODS_LIST = 'GENE_GOODS_LIST';
export const GENE_GOODS_LIST_SUCCESS = 'GENE_GOODS_LIST_SUCCESS';
export const GENE_GOODS_LIST_ERROR = 'GENE_GOODS_LIST_ERROR';
