
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';

export const MESSAGE_COUNT = 'MESSAGE_COUNT';
export const MESSAGE_COUNT_SUCCESS = 'MESSAGE_COUNT_SUCCESS';
export const MESSAGE_COUNT_ERROR = 'MESSAGE_COUNT_ERROR';
