
export const MOBILE_EXIST = 'MOBILE_EXIST';
export const MOBILE_EXIST_SUCCESS = 'MOBILE_EXIST_SUCCESS';
export const MOBILE_EXIST_ERROR = 'MOBILE_EXIST_ERROR';

export const SEND_LOGIN_CODE = 'SEND_LOGIN_CODE';
export const SEND_LOGIN_CODE_SUCCESS = 'SEND_LOGIN_CODE_SUCCESS';
export const SEND_LOGIN_CODE_ERROR = 'SEND_LOGIN_CODE_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


export const CHECK_VERIFY_CODE = 'CHECK_VERIFY_CODE';
export const CHECK_VERIFY_CODE_SUCCESS = 'CHECK_VERIFY_CODE_SUCCESS';
export const CHECK_VERIFY_CODE_ERROR = 'CHECK_VERIFY_CODE_ERROR';
