
export const GOODS_ITEM = 'GOODS_ITEM';
export const GOODS_ITEM_SUCCESS = 'GOODS_ITEM_SUCCESS';
export const GOODS_ITEM_ERROR = 'GOODS_ITEM_ERROR';


export const IMAGE_TEXT = 'IMAGE_TEXT';
export const IMAGE_TEXT_SUCCESS = 'IMAGE_TEXT_SUCCESS';
export const IMAGE_TEXT_ERROR = 'IMAGE_TEXT_ERROR';


export const PROFESSIONAL = 'PROFESSIONAL';
export const PROFESSIONAL_SUCCESS = 'PROFESSIONAL_SUCCESS';
export const PROFESSIONAL_ERROR = 'PROFESSIONAL_ERROR';

export const SAVE_BASE_64_IMG = 'SAVE_BASE_64_IMG';
export const SAVE_BASE_64_IMG_SUCCESS = 'SAVE_BASE_64_IMG_SUCCESS';
export const SAVE_BASE_64_IMG_ERROR = 'SAVE_BASE_64_IMG_ERROR';
